<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG7syPrJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG7syPrJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG7syPrJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG7syPrJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG7syPrJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G7syPrJ',
    'container.build_id' => 'b8af998c',
    'container.build_time' => 1573990443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG7syPrJ');
